version = 1
disable_existing_loggers = false

[formatters.default]
format = "%(asctime)s %(levelname)s: %(message)s [%(name)s]"
datefmt = "%H:%M:%S"

[handlers.console]
class = "logging.StreamHandler"
formatter = "default"
stream = "ext://sys.stderr"

[root]
level = "INFO"
handlers = ["console"]
propagate = false

[loggers."uvicorn.error"]
level = "INFO"
handlers = ["console"]
propagate = false

[loggers."uvicorn.access"]
level = "INFO"
handlers = ["console"]
propagate = false
