"""otps table

Revision ID: effba65ae35e
Revises: 2bb11d4615e4
Create Date: 2025-11-25 21:03:18.525258

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "effba65ae35e"
down_revision: Union[str, Sequence[str], None] = "2bb11d4615e4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "otps",
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("phone", sa.String(), nullable=False),
        sa.Column("intent", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("otp_hash", sa.String(), nullable=False),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("ipaddr", sa.String(), nullable=False),
        sa.Column(
            "metadata", sa.JSON(), server_default=sa.text("'{}'"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_otps_consumed_at"), "otps", ["consumed_at"], unique=False)
    op.create_index(op.f("ix_otps_expires_at"), "otps", ["expires_at"], unique=False)
    op.create_index(op.f("ix_otps_intent"), "otps", ["intent"], unique=False)
    op.create_index(op.f("ix_otps_phone"), "otps", ["phone"], unique=False)
    op.create_index(op.f("ix_otps_status"), "otps", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_otps_status"), table_name="otps")
    op.drop_index(op.f("ix_otps_phone"), table_name="otps")
    op.drop_index(op.f("ix_otps_intent"), table_name="otps")
    op.drop_index(op.f("ix_otps_expires_at"), table_name="otps")
    op.drop_index(op.f("ix_otps_consumed_at"), table_name="otps")
    op.drop_table("otps")
    # ### end Alembic commands ###
