import abc


class HashService(abc.ABC):
    """Abstract base class for services that provide hashing and verification."""

    def hash(self, text: str) -> str:
        """Validates and hashes the input text using the concrete implementation.

        :param text: The plain-text string to hash.
        :return: An opaque hash string, generated by the subclass.
        :raises TypeError: If the input `text` is not a string.
        :raises ValueError: If the input `text` is empty.
        """
        if not isinstance(text, str):
            raise TypeError("The input text must be a string.")
        if not text:
            raise ValueError("The input text cannot be empty.")

        return self._hash_text(text)

    def verify(self, text: str, hashed: str) -> bool:
        """Verifies a text string against a hash using the concrete implementation.

        :param text: The plain-text string to verify.
        :param hashed: The stored hash string to validate against.
        :return: True if the text matches the hash, False otherwise.
        :raises TypeError: If either `text` or `hashed` is not a string.
        :raises ValueError: If either `text` or `hashed` is empty.
        """
        if not isinstance(text, str) or not isinstance(hashed, str):
            raise TypeError("Both text and hashed inputs must be strings.")
        if not text or not hashed:
            raise ValueError("Both text and hashed inputs cannot be empty.")

        return self._verify_hash(text, hashed)

    @abc.abstractmethod
    def _hash_text(self, text: str) -> str:
        """Performs the actual hashing logic."""
        raise NotImplementedError

    @abc.abstractmethod
    def _verify_hash(self, text: str, hashed: str) -> bool:
        """Performs the actual verification logic."""
        raise NotImplementedError
